// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart cortextos-daemon` switches instances without regenerating.
module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: "/Users/schmiegelowfms/cortextos/dist/daemon.js",
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: "/Users/schmiegelowfms/cortextos",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: process.env.CTX_ROOT || "/Users/schmiegelowfms/.cortextos/default",
        CTX_FRAMEWORK_ROOT: "/Users/schmiegelowfms/cortextos",
        CTX_PROJECT_ROOT: "/Users/schmiegelowfms/cortextos",
        CTX_ORG: process.env.CTX_ORG || "schmiegelow",
      },
      // max_restarts + restart_delay is the ultimate crash-storm circuit
      // breaker. If the daemon dies 10 times faster than 5s apart, PM2
      // gives up — the fleet goes fully dead, requiring a manual
      // `pm2 restart cortextos-daemon`. That is intentional: storm
      // protection > fleet uptime during a pathological crash loop.
      // The daemon's uncaughtException handler (src/daemon/index.ts)
      // fires a Telegram alert to the operator at 3+ crashes in 15 min —
      // well before this circuit trips. Do NOT raise these values without
      // also strengthening the upstream fix; the 2026-04-22 storm is a
      // reminder that unchecked auto-restart amplifies one bug into a
      // fleet-wide outage.
      max_restarts: 10,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
